# File: release stage
    
stages:
- stage: Release
  jobs:
    - deployment: 
      environment: 
        name: default-1
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'website'
                  targetPath: '/home/alok/appx/chatroom'

              - task: CmdLine@2
                inputs:
                  script: |
                    cd /home/alok/appx/chatroom/api
                    python3 -m venv env
                    source env/bin/activate
                    pip install -r requirements.txt
                    ps aux | grep chatroom | awk '{print $2;}' | xargs kill -9 2>/dev/null
                    gunicorn --worker-class eventlet -w 1 app:app -n wwwchatroom -b 0.0.0.0:5002 -D
